### ISSUE TITLE
Tutorial on how to create or to modify layouts

### ISSUE THREAD

**Issue by jhuber-de** [Thecakeisgit/LocaleKeyboard.js#6] opened 2016-11-21 17:09 UTC
I would love to help by providing a german keyboard layout but I have no idea how to do that. 
A tutorial on how to create or to modify layouts and also on how to use any of the stuff on this rep would be nice.

**Comment by lowlevl** [comment] 2016-11-21 17:46
Hi @gh7531, I like the idea to create a tutorial, I'll do this very quickly.. Do you think I need to do it on the README.md or on a Wiki or what else ? Please tell me ;D

**Comment by jhuber-de** [comment] 2016-11-21 17:58
I would use the wiki and then link to the wiki in the readme file. But I'm no expert regarding github :)

**Comment by lowlevl** [comment] 2016-11-21 19:11
Done @gh7531 :D 
Wiki : [How to create a locale ?!](https://github.com/Thecakeisgit/LocaleKeyboard.js/wiki/How-to-create-a-locale-%3F!)

Any question ?

**Comment by jhuber-de** [comment] 2016-11-22 19:39
Thanks a lot. On thing to add would be how to obtain the hex values for each key.
Also since the _asciimap array is only 128 items long do you only support the standard ascii code? If so would it be possible to support the whole 8bit extended ascii code? Here is a link to clarify what I'm talking about http://www.asciitable.com/

**Comment by lowlevl** [comment] 2016-11-22 19:43
The problem is the Arduino HID.cpp code, coupled to the Arduino Core who is made for only ascii 128.. @gh7531

**Comment by jhuber-de** [comment] 2016-11-22 20:10
So extended ascii and therefore letters like the german umlauts ä,ü,ö are impossible?

**Comment by lowlevl** [comment] 2016-12-03 22:29
I don't think so.. @gh7531 (Sry for the late ;D) 
Can i close the issue ?

**Closed as completed** 2016-12-04 11:18 UTC
Labels: question
